# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-13 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormModel',
        ),
    ]
